 # -*- coding: utf-8 -*-

column_1 = [
    'Mr. Speaker',
    'Allen',
    'Alonzo',
    'Alvarado',
    'Anchia',
    'Aderson',
    'Ashby',
    'Aycock',
    'Bell',
    'Bohac',
    'Bonnen, D',
    'Bonnen, G',
    'Branch',
    'Burkett',
    'Burnam',
    'Button',
    'Callegari',
    'Canales',
    'Capriglione',
    'Carter',
    'Clardy',
    'Coleman',
    'Collier',
    'Cook',
    'Cortez',
    'Craddick',
    'Creighton',
    'Crownover',
    'Dale',
    'Darby',
    'Davis, J',
    'Davis, S',
    'Davis, Y',
    'Deshotel',
    'Dukes',
    'Dutton',
    'Eiland',
    'Elkins'
]

column_2 = [
    'Fallon',
    'Farias',
    'Farney',
    'Farrar',
    'Fletcher',
    'Flynn',
    'Frank',
    'Frullo',
    'Geren',
    'Giddings',
    'Foldman',
    'Gonzales',
    'González, M',
    'González, N',
    'Gooden',
    'Guerra',
    'Guillen',
    'Gutierrez',
    'Harless',
    'Harper-Brown',
    'Hernandez Luna',
    'Herrero',
    'Hilderbran',
    'Goward',
    'Huberty',
    'Hughes',
    'Hunter',
    'Isaac',
    'Johnson',
    'Kacal',
    'Keffer',
    'King, K',
    'King, P',
    'King, S',
    'King, T',
    'Kleinschmidt',
    'Klick',
    'Kolkhorst'
]

column_3 = [
    'Krause',
    'Kuempel',
    'Larson',
    'Laubenberg',
    'Lavender',
    'Leach',
    'Lewis',
    'Longoria',
    'Lozano',
    'Lucio',
    'Márquez',
    'Martinez',
    'Martinez Fisscher',
    'McClendon',
    'Menéndez',
    'Miles',
    'Miller D',
    'Miller R',
    'Moody',
    'Morrison',
    'Muñoz',
    'Murphy',
    'Naivashtat',
    'Nevårez',
    'Oliveira',
    'Orr',
    'Otto',
    'Paddie',
    'Parker',
    'Patrick',
    'Perez',
    'Perry',
    'Phillips',
    'Pickett',
    'Pitts',
    'Price',
    'Raney',
    'Ratliff'
]

column_4 = [
    'Raymond',
    'Reynolds',
    'Riddle',
    'Ritter',
    'Rodriguez, E',
    'Rodriguez, J',
    'Rose',
    'Sanford',
    'Schaefer',
    'Sheets',
    'Sheffield, J',
    'Sheffield, R',
    'Simmons',
    'Simpson',
    'Smith',
    'Smithee',
    'Springer',
    'Stephenson',
    'Stickland',
    'Taylor',
    'Thompson, E',
    'Thompson, S',
    'Toth',
    'Turner, C',
    'Turner, E.S',
    'Turner, S',
    'Villalba',
    'Villareal',
    'Vo',
    'Walle',
    'White',
    'Workman',
    'Wu',
    'Zedler',
    'Zerwas'
]

representatives = column_1 + column_2 + column_3 + column_4
